[[pages]]
path = "login.py"
name = "Login"
icon = "ğŸ”’"

[[pages]]
path = "pages/chat_page.py"
name = "Threat Intelligence"
icon = "ğŸ”"

[[pages]]
path = "pages/red_blue_emulator.py"
name = "Caldera Emulator"
icon = "ğŸš”"

[[pages]]
path = "pages/wazuh_plotly_js_interactive.py"
name = "Interactive Plot"
icon = "ğŸ‘‰"

[[pages]]
path = "pages/wazuh_plotly_js_four_graphs.py"
name = "Rule Level Graphs"
icon = "ğŸ“Š"

[[pages]]
path = "pages/wazuh_plotly_js.py"
name = "Simple Plot"
icon = "*ï¸âƒ£"

[[pages]]
path = "pages/machine_traffic.py"
name = "VM Traffic"
icon = "ğŸŒ"

[[pages]]
path = "pages/snort.py"
name = "Snort Sniffer"
icon = "ğŸ½"